<a href="https://colab.research.google.com/github/lbushen/pytorch-tutorial/blob/main/intro_to_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import torch

In [7]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# reshape and view

In [9]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [11]:
# reshape if we don't know the number of items using -1

In [12]:
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
my_torch2 = my_torch2.reshape(2, -1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
# reshape and view will update

In [16]:
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
my_torch3 = torch.arange(20)
my_torch3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [20]:
my_torch3[2]= 339
my_torch3

tensor([  0,   1, 339,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19])

In [21]:
my_torch4 = my_torch3.reshape(2, -1)
my_torch4

tensor([[  0,   1, 339,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19]])

In [24]:
#slices
# allow you to grab a slice of your tensor

In [23]:
my_torch5 = torch.arange(10)
my_torch5[7]

tensor(7)

In [25]:
# grab a slice

In [26]:
my_torch8 = my_torch5.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [27]:
# grab the second column

In [28]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [29]:
# return column


In [30]:
my_torch8[:, 1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])