<a href="https://colab.research.google.com/github/lbushen/pytorch-tutorial/blob/main/Math_in_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

In [1]:
# create 2 tensors with same number of items in each

In [4]:
tensor1 = torch.tensor([1,2,3,4])
tensor2 = torch.tensor([5,6,7,8])

In [5]:
# addition

In [6]:
tensor1 + tensor2

tensor([ 6,  8, 10, 12])

In [7]:
torch.add(tensor1, tensor2)

tensor([ 6,  8, 10, 12])

In [8]:
# subtraction

subtraction short version

In [9]:
tensor2 - tensor1

tensor([4, 4, 4, 4])

subtraction long version

In [11]:
torch.sub(tensor2, tensor1)

tensor([4, 4, 4, 4])

In [12]:
# multiplication

In [13]:
tensor1 * tensor2

tensor([ 5, 12, 21, 32])

In [14]:
torch.mul(tensor1, tensor2)

tensor([ 5, 12, 21, 32])

In [15]:
# division


In [16]:
tensor2 / tensor1

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [17]:
torch.div(tensor2, tensor1)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [18]:
# remainders with modulus


In [19]:
tensor2 % tensor1

tensor([0, 0, 1, 0])

In [20]:
torch.remainder(tensor2, tensor1)

tensor([0, 0, 1, 0])

In [21]:
# exponents

In [22]:
torch.pow(tensor1, tensor2)

tensor([    1,    64,  2187, 65536])

In [24]:
# another way for longhand
tensor1.add(tensor2)

tensor([ 6,  8, 10, 12])

In [25]:
# reassignments
tensor1.add_(tensor2)

tensor([ 6,  8, 10, 12])

In [26]:
tensor1

tensor([ 6,  8, 10, 12])